name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 18 * * *"   # 每天自动更新
  workflow_dispatch:        # 支持手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: Ruvikm
      - name: Commit & Push
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git add -A .
          git commit -m "generate 3d profile" --allow-empty
          git push
